import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from  "../context/AuthContext";

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
      <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
